version: "2.1"
volumes:
    user-data:
    user-gg:
services:
  greengrass:
    build: .
    restart: unless-stopped
    privileged: true
    volumes:
       - 'user-data:/user-data'
       - 'user-gg:/greengrass'
